language: cpp
script: make
before_install: 
     - sudo ./Angel/nix-prereqs.sh
     - sudo apt-get update
     - sudo apt-get install --only-upgrade g++
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c9e4605d291c9a8614ec
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: always     # default: false
